name: Despliegue Cloud Scraper Drayage

on:
  workflow_dispatch:

jobs:
  ejecutar-scraper-nube:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Verificar versión de Google Chrome preinstalado
        run: google-chrome --version

      - name: Instalar y conectar Cloudflare WARP (Modo Proxy)
        run: |
          sudo curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update && sudo apt-get install -y cloudflare-warp
          warp-cli --accept-tos registration new
          warp-cli --accept-tos mode proxy
          warp-cli --accept-tos connect
          sleep 5

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install selenium curl_cffi undetected-chromedriver

      - name: Ejecutar Script Híbrido en la Nube
        run: python scrapper.py